### PR TITLE
Auto-initialise autocomplete fields after opening a dialog

### LINKED ISSUE #105: Autocomplete fields inside dialogs are broken
When using an autocomplete field in a UI element form, it doesn't work automatically. You have to add JavaScript that initialises the autocomplete field. I suggest we auto-initialise autocomplete fields after opening a dialog.

### PR DESCRIPTION
**Pull request by DieterHolvoet**
Fixes #105.

### CODE REVIEW

**Review by maximehuran — CHANGES_REQUESTED** [review]
Hi,

Thank you for your pull request. We didn't managed auto-complete because no UI Element used it, but it can be interesting to have it for custom elements.

The better way to do that is like `initUiCollectionForm` in `app.js` 
https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/8cbf0b0d821dc617bd112ba9040bc8508c2e576f/assets/js/app.js#L552

Then retrieve it in `app.html.twig` https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/9ce5020faa5ca68c956088220d7d6c2c88f42c89/src/Resources/views/Admin/app.html.twig#L127

**Comment by DieterHolvoet** [comment]
Do you suggest adding it to the event listener in app.html or to the initUiCollectionForm function in app.js?

**Comment by maximehuran** [comment]
It can be another method to avoid mess : 

```
initAutoCompleteForm(form) {
    document.dispatchEvent(new CustomEvent('monsieurBizRichEditorInitAutoCompleteForm', {
      'detail': {'form': form}
    }));
  }
```

Then

```
document.addEventListener('monsieurBizRichEditorInitAutoCompleteForm', (e) => {
        let form = e.detail.form;
        $(form).find('.sylius-autocomplete').autoComplete(); // I don't know if it works
    });
```

**Comment by DieterHolvoet** [comment]
What do you think about a more generic `monsieurBizRichEditorInitForm` event and two subscribers, one for initialising CollectionForm and one for initialising autocomplete.

**Comment by maximehuran** [comment]
Or a generic event like you said `monsieurBizRichEditorInitForm` and one event subscriber ^^

**Comment by DieterHolvoet** [comment]
@maximehuran did the changes, let me know what you think.

**Comment by maximehuran** [comment]
I made a rebase from master but I cannot force push with lease in your branch.
Can you resolve the conflict ?

**Review by maximehuran — APPROVED** [review]

**Comment by DieterHolvoet** [comment]
Done!

**Comment by maximehuran** [comment]
Thank you @DieterHolvoet ! 🥇

**Pull request merged**
