### PR TITLE
Add the ability to nest a rich editor inside another UIElement

### LINKED ISSUE #172: [FEATURE] Nested UI elements
We had this use case where we'd like to reuse some UI elements but wrap them in some container.
I tried to do a simple RicheditorType on a UIelement field but doesn't seems to work.

What do you think ?

### PR DESCRIPTION
**Pull request by julien1619**
Hi everyone!

This PR aims to add the ability to use the rich editor inside another UIElement, it allows the user to create a row/column component.

To add this feature, two main changes were done:
- Try to init the editor after each formInit event, and avoid creating an already created editor
- Scope the dialogs to avoid any overlap

closes #172

### CODE REVIEW

**Comment by maximehuran** [comment]
Hi @julien1619 !

It's a cool feature we want to have so thank you :)
Do you think you can add a sample UI Element in the test application using this feature ?

**Comment by julien1619** [comment]
Yes, I will add a Row component today ;)

**Comment by julien1619** [comment]
It's done and tested :)

**Comment by maximehuran** [comment]
Very nice work 🚀 
I have a suggestion about the element.

Maybe it could be nice to have a "2 columns" element instead.
WDYTOT ?

That I cannot push on your branch, you can check this commit : 

https://github.com/monsieurbiz/SyliusRichEditorPlugin/pull/203/commits/f455d51886f42a1b70b8da8a051e95fc778583c1

**Comment by julien1619** [comment]
I tend to prefer the multi-columns one because our use case is to put multiple components (between 2 and 5) in columns on desktop. So my component doesn't limit the number of column, but it doesn't allow to put multiple elements inside it.

One solution to have both way would be to have two components :

- a row/multi-column component: same as the one I proposed.
- a column component: a simple RichText, just rendering the components as-is.

What do you think? I would understand if you prefer to keep it simple, but I think it could work well.

**Comment by maximehuran** [comment]
Yes it could be great.
Can you check this commit ? It's done, I updated README and also add some borders in admin to understand the layout separations.

https://github.com/monsieurbiz/SyliusRichEditorPlugin/pull/203/commits/1120edaf6da138459d55682b4fff00f91a84fdb1

I still have an issue in Admin.
If I use the column element in row element, the Shop template is used for the Column element.

Example : 

https://github.com/monsieurbiz/SyliusRichEditorPlugin/assets/11380627/af68f9f5-f949-4290-9bb7-df64ad7492db

**Comment by julien1619** [comment]
It seems perfect to me!

**Comment by maximehuran** [comment]
I still have an issue in Admin.
If I use the column element in row element, the Shop template is used for the Column element.

I will try to check this tomorrow, if you have a clue I get it 😉

**Comment by julien1619** [comment]
I've found why. In fact the twig filter always render the shop element, not the admin one. When you try to render the row element, the column will be rendered with the front element. Here it is:

[`$template = $uiElement->getFrontRenderTemplate();` ](https://github.com/monsieurbiz/SyliusRichEditorPlugin/blob/master/src/Twig/RichEditorExtension.php#L161)

Maybe you can create the same filters than the existing ones but for the admin part and use it inside the column and row?

```diff
public function getFilters(): array
    {
        return [
            new TwigFilter('monsieurbiz_richeditor_render_field', [$this, 'renderField'], ['is_safe' => ['html'], 'needs_context' => true]),
            new TwigFilter('monsieurbiz_richeditor_render_elements', [$this, 'renderElements'], ['is_safe' => ['html'], 'needs_context' => true]),
            new TwigFilter('monsieurbiz_richeditor_render_element', [$this, 'renderElement'], ['is_safe' => ['html'], 'needs_context' => true]),
+           new TwigFilter('monsieurbiz_richeditor_render_admin_field', [$this, 'renderAdminField'], ['is_safe' => ['html'], 'needs_context' => true]),
+           new TwigFilter('monsieurbiz_richeditor_render_admin_elements', [$this, 'renderAdminElements'], ['is_safe' => ['html'], 'needs_context' => true]),
+           new TwigFilter('monsieurbiz_richeditor_render_admin_element', [$this, 'renderAdminElement'], ['is_safe' => ['html'], 'needs_context' => true]),
        ];
    }
```

**Comment by maximehuran** [comment]
It will be done automatically using the firewall context : 

https://github.com/monsieurbiz/SyliusRichEditorPlugin/pull/203/commits/a47e7faf6d4767852925d4a485337070981ee01c

**Comment by julien1619** [comment]
I think we can close this one and merge the other one.

**Comment by maximehuran** [comment]
Thank you @julien1619 🚀

**Pull request closed without merging**
